// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type { DiscordCallbackData, DiscordCallbackResponses, DiscordLoginData, ExchangeTokenData, ExchangeTokenResponses, FinishMergeTaskData, FinishMergeTaskErrors, FinishMergeTaskResponses, FinishTaskData, FinishTaskErrors, FinishTaskRenderingData, FinishTaskRenderingErrors, FinishTaskRenderingResponses, FinishTaskResponses, GetCurrentNode2Data, GetCurrentNode2Responses, GetCurrentNodeData, GetCurrentNodeResponses, GetMergeTaskUploadUrlsData, GetMergeTaskUploadUrlsErrors, GetMergeTaskUploadUrlsResponses, GetNextTask2Data, GetNextTask2Responses, GetNextTaskData, GetNextTaskResponses, NotifyRenderNodeShutdownData, NotifyRenderNodeShutdownResponses, RefreshTokenData, RefreshTokenResponses, ReportTaskProgressData, ReportTaskProgressErrors, ReportTaskProgressResponses, RevokeAllRefreshTokensData, RevokeAllRefreshTokensResponses, RevokeRefreshTokenData, RevokeRefreshTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create refresh and access tokens from an auth code
 */
export const exchangeToken = <ThrowOnError extends boolean = true>(options: Options<ExchangeTokenData, ThrowOnError>): RequestResult<ExchangeTokenResponses, unknown, ThrowOnError> => options.client.post<ExchangeTokenResponses, unknown, ThrowOnError>({
    url: '/auth/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a new access token
 *
 * This creates a new short-lived access token. The refresh token will be rotated and a new refresh token is returned, too.
 */
export const refreshToken = <ThrowOnError extends boolean = true>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, unknown, ThrowOnError> => options.client.post<RefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke a refresh token
 *
 * This revokes the specified refresh token. Access tokens generated by this refresh token will continue to work until they expire.
 */
export const revokeRefreshToken = <ThrowOnError extends boolean = true>(options: Options<RevokeRefreshTokenData, ThrowOnError>): RequestResult<RevokeRefreshTokenResponses, unknown, ThrowOnError> => options.client.post<RevokeRefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke all refresh tokens
 *
 * This revokes all refresh token of the current user. All access tokens generated before will continue to work until they expire.
 */
export const revokeAllRefreshTokens = <ThrowOnError extends boolean = true>(options: Options<RevokeAllRefreshTokensData, ThrowOnError>): RequestResult<RevokeAllRefreshTokensResponses, unknown, ThrowOnError> => options.client.post<RevokeAllRefreshTokensResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/auth/revoke-all',
    ...options
});

/**
 * Initiate the Discord OAuth login
 */
export const discordLogin = <ThrowOnError extends boolean = true>(options: Options<DiscordLoginData, ThrowOnError>): RequestResult<unknown, unknown, ThrowOnError> => options.client.get<unknown, unknown, ThrowOnError>({ url: '/auth/discord', ...options });

/**
 * Finish Discord OAuth login
 */
export const discordCallback = <ThrowOnError extends boolean = true>(options: Options<DiscordCallbackData, ThrowOnError>): RequestResult<DiscordCallbackResponses, unknown, ThrowOnError> => options.client.get<DiscordCallbackResponses, unknown, ThrowOnError>({ url: '/auth/discord/callback', ...options });

/**
 * Get the current render node
 */
export const getCurrentNode = <ThrowOnError extends boolean = true>(options: Options<GetCurrentNodeData, ThrowOnError>): RequestResult<GetCurrentNodeResponses, unknown, ThrowOnError> => options.client.get<GetCurrentNodeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'renderer-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me',
    ...options
});

/**
 * Get the next task for this node
 */
export const getNextTask = <ThrowOnError extends boolean = true>(options: Options<GetNextTaskData, ThrowOnError>): RequestResult<GetNextTaskResponses, unknown, ThrowOnError> => options.client.get<GetNextTaskResponses, unknown, ThrowOnError>({
    security: [{
            key: 'renderer-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/next',
    ...options
});

/**
 * Get result upload URLs and mark the task as uploading
 */
export const finishTaskRendering = <ThrowOnError extends boolean = true>(options: Options<FinishTaskRenderingData, ThrowOnError>): RequestResult<FinishTaskRenderingResponses, FinishTaskRenderingErrors, ThrowOnError> => options.client.post<FinishTaskRenderingResponses, FinishTaskRenderingErrors, ThrowOnError>({
    security: [{
            key: 'renderer-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/{id}/upload',
    ...options
});

/**
 * Mark the task as completed after uploading the results
 */
export const finishTask = <ThrowOnError extends boolean = true>(options: Options<FinishTaskData, ThrowOnError>): RequestResult<FinishTaskResponses, FinishTaskErrors, ThrowOnError> => options.client.post<FinishTaskResponses, FinishTaskErrors, ThrowOnError>({
    security: [{
            key: 'renderer-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/{id}/finish',
    ...options
});

/**
 * Report the rendering progress of this task
 */
export const reportTaskProgress = <ThrowOnError extends boolean = true>(options: Options<ReportTaskProgressData, ThrowOnError>): RequestResult<ReportTaskProgressResponses, ReportTaskProgressErrors, ThrowOnError> => options.client.post<ReportTaskProgressResponses, ReportTaskProgressErrors, ThrowOnError>({
    security: [{
            key: 'renderer-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/{id}/progress',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Notify the scheduler about the shutdown of this render node. This allows it to e.g. re-assign tasks without waiting for them to become stale.
 */
export const notifyRenderNodeShutdown = <ThrowOnError extends boolean = true>(options: Options<NotifyRenderNodeShutdownData, ThrowOnError>): RequestResult<NotifyRenderNodeShutdownResponses, unknown, ThrowOnError> => options.client.post<NotifyRenderNodeShutdownResponses, unknown, ThrowOnError>({
    security: [{
            key: 'renderer-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/shutdown',
    ...options
});

/**
 * Get the current worker node
 */
export const getCurrentNode2 = <ThrowOnError extends boolean = true>(options: Options<GetCurrentNode2Data, ThrowOnError>): RequestResult<GetCurrentNode2Responses, unknown, ThrowOnError> => options.client.get<GetCurrentNode2Responses, unknown, ThrowOnError>({
    security: [{
            key: 'worker-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/worker-nodes/me',
    ...options
});

/**
 * Get the next task for this worker node
 */
export const getNextTask2 = <ThrowOnError extends boolean = true>(options: Options<GetNextTask2Data, ThrowOnError>): RequestResult<GetNextTask2Responses, unknown, ThrowOnError> => options.client.get<GetNextTask2Responses, unknown, ThrowOnError>({
    security: [{
            key: 'worker-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/worker-nodes/me/tasks/next',
    ...options
});

/**
 * Get result upload URLs and mark the merge task as uploading
 */
export const getMergeTaskUploadUrls = <ThrowOnError extends boolean = true>(options: Options<GetMergeTaskUploadUrlsData, ThrowOnError>): RequestResult<GetMergeTaskUploadUrlsResponses, GetMergeTaskUploadUrlsErrors, ThrowOnError> => options.client.post<GetMergeTaskUploadUrlsResponses, GetMergeTaskUploadUrlsErrors, ThrowOnError>({
    security: [{
            key: 'worker-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/worker-nodes/me/tasks/merge/{jobId}/upload',
    ...options
});

/**
 * Mark the merge task as completed after uploading the results
 */
export const finishMergeTask = <ThrowOnError extends boolean = true>(options: Options<FinishMergeTaskData, ThrowOnError>): RequestResult<FinishMergeTaskResponses, FinishMergeTaskErrors, ThrowOnError> => options.client.post<FinishMergeTaskResponses, FinishMergeTaskErrors, ThrowOnError>({
    security: [{
            key: 'worker-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/worker-nodes/me/tasks/merge/{jobId}/finish',
    ...options
});
