// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AuthenticateDto = {
    code: string;
};

export type TokenResponse = {
    refreshToken: {
        expiresAt: string;
        token: string;
    };
    accessToken: string;
};

export type RefreshTokenDto = {
    refreshToken: string;
};

export type RenderNodeResponse = {
    id: number;
    name?: string;
    enabled: boolean;
    lastSeenAt: string;
    createdAt: string;
    updatedAt: string;
};

export type NextTaskResponse = {
    id: number;
    job: {
        id: number;
        width: number;
        height: number;
    };
    spp: number;
    tile: {
        x: number;
        y: number;
        width: number;
        height: number;
    };
    files: {
        scene: {
            url: string;
        };
        octree: {
            url: string;
        };
        emittergrid?: {
            url: string;
        };
        resourcePacks: Array<{
            id: number;
            url: string;
        }>;
    };
};

export type FinishTaskRenderingResponse = {
    uploadUrls: {
        image: string;
        dump?: string;
    };
};

export type ReportTaskProgressDto = {
    spp: number;
    sps: number;
};

export type NextWorkerTaskResponse = {
    type: 'merge';
    job: {
        id: number;
        width: number;
        height: number;
    };
    tiles: Array<{
        x: number;
        y: number;
        width: number;
        height: number;
        image: {
            url: string;
        };
        dump?: {
            url: string;
        };
    }>;
};

export type FinishMergeTaskResponse = {
    uploadUrls: {
        /**
         * The URL to upload the final merged image to (as PNG)
         */
        image: string;
        /**
         * The URL to upload a thumbnail of the final merged image to (as JPEG with a resolution of max 512x512 and quality of 80%)
         */
        thumbnailImage: string;
        /**
         * The URL to upload the dump file to
         */
        dump?: string;
    };
};

export type ExchangeTokenData = {
    body: AuthenticateDto;
    path?: never;
    query?: never;
    url: '/auth/exchange';
};

export type ExchangeTokenResponses = {
    201: TokenResponse;
};

export type ExchangeTokenResponse = ExchangeTokenResponses[keyof ExchangeTokenResponses];

export type RefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenResponses = {
    201: TokenResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type RevokeRefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/revoke';
};

export type RevokeRefreshTokenResponses = {
    204: void;
};

export type RevokeRefreshTokenResponse = RevokeRefreshTokenResponses[keyof RevokeRefreshTokenResponses];

export type RevokeAllRefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/revoke-all';
};

export type RevokeAllRefreshTokensResponses = {
    204: void;
};

export type RevokeAllRefreshTokensResponse = RevokeAllRefreshTokensResponses[keyof RevokeAllRefreshTokensResponses];

export type DiscordLoginData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Redirect destination after successful login
         */
        returnTo?: 'website' | 'localhost';
        /**
         * State that will be included in the redirect URL after successful login
         */
        state?: unknown;
    };
    url: '/auth/discord';
};

export type DiscordLoginResponses = {
    200: unknown;
};

export type DiscordCallbackData = {
    body?: never;
    path?: never;
    query: {
        state: string;
    };
    url: '/auth/discord/callback';
};

export type DiscordCallbackResponses = {
    /**
     * Returns the auth code if "returnTo" was not specified
     */
    200: {
        /**
         * Auth code that can be used to get a refresh token from the /auth/exchange endpoint. Only valid for a very short time.
         */
        code: string;
    };
};

export type DiscordCallbackResponse = DiscordCallbackResponses[keyof DiscordCallbackResponses];

export type GetCurrentNodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes/me';
};

export type GetCurrentNodeResponses = {
    default: RenderNodeResponse;
};

export type GetCurrentNodeResponse = GetCurrentNodeResponses[keyof GetCurrentNodeResponses];

export type GetNextTaskData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes/me/tasks/next';
};

export type GetNextTaskResponses = {
    /**
     * The task this render node should render next
     */
    200: NextTaskResponse;
    /**
     * There is no task to render at this time
     */
    204: void;
};

export type GetNextTaskResponse = GetNextTaskResponses[keyof GetNextTaskResponses];

export type FinishTaskRenderingData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/me/tasks/{id}/upload';
};

export type FinishTaskRenderingErrors = {
    /**
     * The task is not being rendered by this render node or already completed
     */
    409: unknown;
};

export type FinishTaskRenderingResponses = {
    /**
     * URLs to upload the render results to
     */
    200: FinishTaskRenderingResponse;
};

export type FinishTaskRenderingResponse2 = FinishTaskRenderingResponses[keyof FinishTaskRenderingResponses];

export type FinishTaskData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/me/tasks/{id}/finish';
};

export type FinishTaskErrors = {
    /**
     * The task can not be finished or required result files are missing
     */
    409: unknown;
};

export type FinishTaskResponses = {
    /**
     * Task marked as completed
     */
    202: unknown;
};

export type ReportTaskProgressData = {
    body: ReportTaskProgressDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/me/tasks/{id}/progress';
};

export type ReportTaskProgressErrors = {
    /**
     * The task is not assigned to this render node or was cancelled. The render node should stop rendering it.
     */
    409: unknown;
};

export type ReportTaskProgressResponses = {
    /**
     * Task progress updated
     */
    204: void;
};

export type ReportTaskProgressResponse = ReportTaskProgressResponses[keyof ReportTaskProgressResponses];

export type NotifyRenderNodeShutdownData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes/me/shutdown';
};

export type NotifyRenderNodeShutdownResponses = {
    204: void;
};

export type NotifyRenderNodeShutdownResponse = NotifyRenderNodeShutdownResponses[keyof NotifyRenderNodeShutdownResponses];

export type GetCurrentNode2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/worker-nodes/me';
};

export type GetCurrentNode2Responses = {
    default: RenderNodeResponse;
};

export type GetCurrentNode2Response = GetCurrentNode2Responses[keyof GetCurrentNode2Responses];

export type GetNextTask2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/worker-nodes/me/tasks/next';
};

export type GetNextTask2Responses = {
    /**
     * The task this worker node should perform next
     */
    200: NextWorkerTaskResponse;
    /**
     * There is no task at this time
     */
    204: void;
};

export type GetNextTask2Response = GetNextTask2Responses[keyof GetNextTask2Responses];

export type GetMergeTaskUploadUrlsData = {
    body?: never;
    path: {
        jobId: number;
    };
    query?: never;
    url: '/worker-nodes/me/tasks/merge/{jobId}/upload';
};

export type GetMergeTaskUploadUrlsErrors = {
    /**
     * The task is not being rendered by this render node or already completed
     */
    409: unknown;
};

export type GetMergeTaskUploadUrlsResponses = {
    /**
     * URLs to upload the merge results to
     */
    200: FinishMergeTaskResponse;
};

export type GetMergeTaskUploadUrlsResponse = GetMergeTaskUploadUrlsResponses[keyof GetMergeTaskUploadUrlsResponses];

export type FinishMergeTaskData = {
    body?: never;
    path: {
        jobId: number;
    };
    query?: never;
    url: '/worker-nodes/me/tasks/merge/{jobId}/finish';
};

export type FinishMergeTaskErrors = {
    /**
     * The merge task can not be finished or required result files are missing
     */
    409: unknown;
};

export type FinishMergeTaskResponses = {
    /**
     * Merge marked as completed
     */
    202: unknown;
};
