// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type { AbortJobData, AbortJobErrors, AbortJobResponses, CreateJobData, CreateJobResponses, CreateNodeData, CreateNodeResponses, GetCurrentUserData, GetCurrentUserJobData, GetCurrentUserJobResponses, GetCurrentUserJobsData, GetCurrentUserJobsResponses, GetCurrentUserNodesData, GetCurrentUserNodesResponses, GetCurrentUserResponses, GetJobFileData, GetJobFileErrors, GetJobFileResponses, GetJobResultFileData, GetJobResultFileErrors, GetJobResultFileResponses, GetJobTilesData, GetJobTilesErrors, GetJobTilesResponses, GetPublicStatsData, GetPublicStatsResponses, GetResourcePacksData, GetResourcePacksResponses, ResetNodeTokenData, ResetNodeTokenResponses, StartJobData, StartJobErrors, StartJobResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get the current user
 */
export const getCurrentUser = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options
});

/**
 * Get the render nodes of the current user
 */
export const getCurrentUserNodes = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserNodesData, ThrowOnError>): RequestResult<GetCurrentUserNodesResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserNodesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/nodes',
    ...options
});

/**
 * Get the render jobs of the current user
 */
export const getCurrentUserJobs = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserJobsData, ThrowOnError>): RequestResult<GetCurrentUserJobsResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserJobsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/jobs',
    ...options
});

/**
 * Get a render job of the current user
 */
export const getCurrentUserJob = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserJobData, ThrowOnError>): RequestResult<GetCurrentUserJobResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserJobResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/jobs/{id}',
    ...options
});

/**
 * Get the download URL for a result file of a render job of the current user
 */
export const getJobResultFile = <ThrowOnError extends boolean = true>(options: Options<GetJobResultFileData, ThrowOnError>): RequestResult<GetJobResultFileResponses, GetJobResultFileErrors, ThrowOnError> => options.client.get<GetJobResultFileResponses, GetJobResultFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me/jobs/{id}/results/{file}',
    ...options
});

/**
 * Create a new render node
 */
export const createNode = <ThrowOnError extends boolean = true>(options: Options<CreateNodeData, ThrowOnError>): RequestResult<CreateNodeResponses, unknown, ThrowOnError> => options.client.post<CreateNodeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/nodes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset the authentication token of a render node
 */
export const resetNodeToken = <ThrowOnError extends boolean = true>(options: Options<ResetNodeTokenData, ThrowOnError>): RequestResult<ResetNodeTokenResponses, unknown, ThrowOnError> => options.client.post<ResetNodeTokenResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/nodes/{id}/reset-token',
    ...options
});

/**
 * Create a render job
 */
export const createJob = <ThrowOnError extends boolean = true>(options: Options<CreateJobData, ThrowOnError>): RequestResult<CreateJobResponses, unknown, ThrowOnError> => options.client.post<CreateJobResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start a render job
 *
 * Call this after all required files have been uploaded
 */
export const startJob = <ThrowOnError extends boolean = true>(options: Options<StartJobData, ThrowOnError>): RequestResult<StartJobResponses, StartJobErrors, ThrowOnError> => options.client.post<StartJobResponses, StartJobErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/jobs/{id}/start',
    ...options
});

/**
 * Get the download url of a scene file of a job
 */
export const getJobFile = <ThrowOnError extends boolean = true>(options: Options<GetJobFileData, ThrowOnError>): RequestResult<GetJobFileResponses, GetJobFileErrors, ThrowOnError> => options.client.get<GetJobFileResponses, GetJobFileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/jobs/{id}/files/{file}',
    ...options
});

/**
 * Abort a job
 */
export const abortJob = <ThrowOnError extends boolean = true>(options: Options<AbortJobData, ThrowOnError>): RequestResult<AbortJobResponses, AbortJobErrors, ThrowOnError> => options.client.post<AbortJobResponses, AbortJobErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/jobs/{id}/abort',
    ...options
});

/**
 * Get the tiles of a job
 */
export const getJobTiles = <ThrowOnError extends boolean = true>(options: Options<GetJobTilesData, ThrowOnError>): RequestResult<GetJobTilesResponses, GetJobTilesErrors, ThrowOnError> => options.client.get<GetJobTilesResponses, GetJobTilesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/jobs/{id}/tiles',
    ...options
});

/**
 * Get all available resource packs
 */
export const getResourcePacks = <ThrowOnError extends boolean = true>(options: Options<GetResourcePacksData, ThrowOnError>): RequestResult<GetResourcePacksResponses, unknown, ThrowOnError> => options.client.get<GetResourcePacksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/resource-packs',
    ...options
});

/**
 * Get public stats about the service
 */
export const getPublicStats = <ThrowOnError extends boolean = true>(options: Options<GetPublicStatsData, ThrowOnError>): RequestResult<GetPublicStatsResponses, unknown, ThrowOnError> => options.client.get<GetPublicStatsResponses, unknown, ThrowOnError>({ url: '/stats', ...options });
