// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type UserResponse = {
    id: number;
    displayName: string;
    avatarUrl: string | null;
    credits: string;
};

export type UserNodeResponse = {
    id: number;
    name?: string | null;
    lastSeenAt?: string | null;
};

export type Order = 'asc' | 'desc';

export type CreditTransactionType = 'job_fee' | 'job_refund' | 'render_reward' | 'weekly_grant' | 'admin_adjustment';

export type UserTransaction = {
    id: number;
    /**
     * Signed credit balance change: charges are negative, rewards are positive
     */
    amount: string;
    type: CreditTransactionType;
    job?: {
        id: number;
    } | null;
    task?: {
        id: number;
    } | null;
    note: string | null;
    details: {
        [key: string]: unknown;
    } | null;
    createdAt: string;
};

export type CurrentPage = {
    page: number;
    size: number;
};

export type PaginationInfo = {
    page: CurrentPage;
    totalCount: number;
};

export type UserTransactionsResponse = {
    data: Array<UserTransaction>;
    extra: PaginationInfo;
};

export type JobStatus = 'draft' | 'queued' | 'running' | 'merge_pending' | 'merge_running' | 'completed' | 'aborted';

export type UserJob = {
    id: number;
    status: JobStatus;
    progress: number;
    spp: number;
    width: number;
    height: number;
    hasEmitterGrid: boolean;
    createDump: boolean;
    createdAt: string;
    startedAt?: string | null;
    finishedAt?: string | null;
    abortedAt?: string | null;
    thumbnailUrl?: string;
};

export type UserJobsResponse = {
    data: Array<UserJob>;
    extra: PaginationInfo;
};

export type RenderJobEventType = 'task_assigned' | 'task_started' | 'task_completed' | 'task_requeued' | 'task_failed' | 'job_queued' | 'job_completed' | 'job_cancelled';

export type RenderJobEventVisibility = 'user' | 'admin';

export type UserJobHistoryEvent = {
    id: number;
    type: RenderJobEventType;
    visibility: RenderJobEventVisibility;
    job?: {
        id: number;
    };
    task?: {
        id: number;
    } | null;
    node?: {
        id: number;
        type: 'renderer' | 'worker';
    } | null;
    reason?: {
        code: string;
        message?: string;
    } | null;
    createdAt: string;
};

export type UserJobHistoryResponse = {
    data: Array<UserJobHistoryEvent>;
    extra: PaginationInfo;
};

export type UrlResponse = {
    url: string;
};

export type CreateNodeDto = {
    name?: string;
};

export type CreateNodeResponse = {
    id: number;
    /**
     * Render node token (can not be retrieved again later)
     */
    token: string;
};

export type ResetNodeTokenResponse = {
    /**
     * New render node token (can not be retrieved again later)
     */
    token: string;
};

export type EstimateJobCostDto = {
    width: number;
    height: number;
    spp: number;
};

export type EstimateJobCostResponse = {
    /**
     * Estimated work units as an integer string
     */
    workUnits: string;
    /**
     * Credit charge as an integer string; currently 1 credit per work unit
     */
    credits: string;
};

export type ResourcePackDto = {
    /**
     * Resource pack ID
     */
    id: number;
};

export type CreateJobDto = {
    spp: number;
    width: number;
    height: number;
    createDump?: boolean;
    resourcePacks: Array<ResourcePackDto>;
};

export type CreateJobResponse = {
    id: number;
    uploadUrls: {
        scene: string;
        octree: string;
        emittergrid: string;
    };
};

export type TileResponse = {
    /**
     * Horizontal position of the tile in pixels
     */
    x: number;
    /**
     * Vertical position of the tile in pixels
     */
    y: number;
    /**
     * Width of the tile in pixels
     */
    width: number;
    /**
     * Height of the tile in pixels
     */
    height: number;
    /**
     * Rendering progress of the tile
     */
    progress: number;
    /**
     * URL to access the rendered tile image in PNG format. The URL is guaranteed to remain valid for at least one hour after it is requested.
     */
    url: string | null;
};

export type ResourcePackResponse = {
    /**
     * The ID of this resource pack that can be used when creating a render job
     */
    id: number;
    /**
     * The name of this resource pack
     */
    name: string;
    /**
     * A description of this resource pack
     */
    description: string;
};

export type PublicStatsResponse = {
    nodes?: {
        connected: number;
        rendering: number;
    };
    /**
     * Approximate total current rendering speed in samples per second
     */
    totalSamplesPerSeconds: number;
    jobs?: {
        queued: number;
        running: number;
    };
};

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserResponses = {
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetCurrentUserNodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/nodes';
};

export type GetCurrentUserNodesResponses = {
    200: Array<UserNodeResponse>;
};

export type GetCurrentUserNodesResponse = GetCurrentUserNodesResponses[keyof GetCurrentUserNodesResponses];

export type GetCurrentUserTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        sort?: 'createdAt';
        order?: Order;
        page?: number;
        limit?: number;
    };
    url: '/users/me/transactions';
};

export type GetCurrentUserTransactionsResponses = {
    200: UserTransactionsResponse;
};

export type GetCurrentUserTransactionsResponse = GetCurrentUserTransactionsResponses[keyof GetCurrentUserTransactionsResponses];

export type GetCurrentUserJobsData = {
    body?: never;
    path?: never;
    query?: {
        status?: Array<JobStatus>;
        sort?: 'createdAt' | 'startedAt' | 'finishedAt';
        order?: Order;
        page?: number;
        limit?: number;
    };
    url: '/users/me/jobs';
};

export type GetCurrentUserJobsResponses = {
    200: UserJobsResponse;
};

export type GetCurrentUserJobsResponse = GetCurrentUserJobsResponses[keyof GetCurrentUserJobsResponses];

export type GetCurrentUserJobHistoryData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        sort?: 'createdAt';
        order?: Order;
        page?: number;
        limit?: number;
    };
    url: '/users/me/jobs/{id}/history';
};

export type GetCurrentUserJobHistoryErrors = {
    /**
     * Job not found or not owned by the current user
     */
    404: unknown;
};

export type GetCurrentUserJobHistoryResponses = {
    200: UserJobHistoryResponse;
};

export type GetCurrentUserJobHistoryResponse = GetCurrentUserJobHistoryResponses[keyof GetCurrentUserJobHistoryResponses];

export type GetCurrentUserJobData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/me/jobs/{id}';
};

export type GetCurrentUserJobResponses = {
    200: UserJob;
};

export type GetCurrentUserJobResponse = GetCurrentUserJobResponses[keyof GetCurrentUserJobResponses];

export type GetJobResultFileData = {
    body?: never;
    path: {
        id: number;
        /**
         * The dump is only available if the job was created with createDump set to true
         */
        file: 'image' | 'dump';
    };
    query?: never;
    url: '/users/me/jobs/{id}/results/{file}';
};

export type GetJobResultFileErrors = {
    /**
     *  The requested file is invalid or not available for this job
     */
    400: unknown;
};

export type GetJobResultFileResponses = {
    /**
     * A download URL for the requested file, valid for at least 1 hour
     */
    200: UrlResponse;
};

export type GetJobResultFileResponse = GetJobResultFileResponses[keyof GetJobResultFileResponses];

export type CreateNodeData = {
    body: CreateNodeDto;
    path?: never;
    query?: never;
    url: '/nodes';
};

export type CreateNodeResponses = {
    201: CreateNodeResponse;
};

export type CreateNodeResponse2 = CreateNodeResponses[keyof CreateNodeResponses];

export type ResetNodeTokenData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/{id}/reset-token';
};

export type ResetNodeTokenResponses = {
    200: ResetNodeTokenResponse;
};

export type ResetNodeTokenResponse2 = ResetNodeTokenResponses[keyof ResetNodeTokenResponses];

export type EstimateJobCostData = {
    body: EstimateJobCostDto;
    path?: never;
    query?: never;
    url: '/jobs/cost-estimate';
};

export type EstimateJobCostErrors = {
    /**
     * Invalid dimensions, SPP or work unit overflow
     */
    400: unknown;
};

export type EstimateJobCostResponses = {
    200: EstimateJobCostResponse;
};

export type EstimateJobCostResponse2 = EstimateJobCostResponses[keyof EstimateJobCostResponses];

export type CreateJobData = {
    body: CreateJobDto;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type CreateJobResponses = {
    /**
     * The job was created and scene files can now be uploaded
     */
    201: CreateJobResponse;
};

export type CreateJobResponse2 = CreateJobResponses[keyof CreateJobResponses];

export type StartJobData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/jobs/{id}/start';
};

export type StartJobErrors = {
    /**
     * The job is not a draft or required scene files are missing
     */
    409: unknown;
};

export type StartJobResponses = {
    /**
     * The job has been queued
     */
    202: unknown;
};

export type GetJobFileData = {
    body?: never;
    path: {
        id: number;
        file: 'scene' | 'octree' | 'emittergrid';
    };
    query?: never;
    url: '/jobs/{id}/files/{file}';
};

export type GetJobFileErrors = {
    /**
     * The file does not exist
     */
    404: unknown;
};

export type GetJobFileResponses = {
    /**
     * A download URL for the requested file, valid for at least 1 hour
     */
    200: UrlResponse;
};

export type GetJobFileResponse = GetJobFileResponses[keyof GetJobFileResponses];

export type AbortJobData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/jobs/{id}/abort';
};

export type AbortJobErrors = {
    /**
     * The job does not exist or the user cannot access it
     */
    404: unknown;
    /**
     * The job could not be aborted because it is not queued or running
     */
    409: unknown;
};

export type AbortJobResponses = {
    /**
     * The job was aborted
     */
    204: void;
};

export type AbortJobResponse = AbortJobResponses[keyof AbortJobResponses];

export type GetJobTilesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/jobs/{id}/tiles';
};

export type GetJobTilesErrors = {
    /**
     * The job does not exist or the user cannot access it
     */
    404: unknown;
};

export type GetJobTilesResponses = {
    /**
     * The tiles sorted by row and then column (i.e. the first tile is top left, the last tile is bottom right)
     */
    200: Array<TileResponse>;
};

export type GetJobTilesResponse = GetJobTilesResponses[keyof GetJobTilesResponses];

export type GetResourcePacksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/resource-packs';
};

export type GetResourcePacksResponses = {
    200: Array<ResourcePackResponse>;
};

export type GetResourcePacksResponse = GetResourcePacksResponses[keyof GetResourcePacksResponses];

export type GetPublicStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetPublicStatsResponses = {
    200: PublicStatsResponse;
};

export type GetPublicStatsResponse = GetPublicStatsResponses[keyof GetPublicStatsResponses];
